name: Publish Backend Docker Image

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/backend-docker.yml'
      - 'src/**'
      - '!src/BUTR.Site.NexusMods.Client/**'
      - 'build/**'
  workflow_dispatch:

jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: BUTR
        password: ${{ secrets.TOKEN_GPR }}

    - name: Build and Push
      run: dotnet publish src/BUTR.Site.NexusMods.Server --os linux --arch x64 -p:PublishProfile=DefaultContainer;

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Trigger deploy-self-hosted.yml
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.TOKEN_GPR }}
        repository: BUTR/BUTR.Site.NexusMods 
        event-type: deploy-docker-image
        
