name: Deploy Docker Image on Self-Hosted

on:
  repository_dispatch:
    types:
      - deploy-docker-image
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: 'self-hosted-backend'
      url: 'https://vps-crashreporter.aragas.org'
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        #host: ${{ secrets.HOST }}
        host: ${{ secrets.HOST_2 }}
        #username: ${{ secrets.USERNAME }}
        username: ${{ secrets.USERNAME_2 }}
        #password: ${{ secrets.PASSWORD }}
        password: ${{ secrets.PASSWORD_2 }}
        #port: ${{ secrets.PORT }}
        port: ${{ secrets.PORT_2 }}
        script: |
          docker image pull ghcr.io/butr/crashreportviewer;
          docker stack deploy --prune --resolve-image always -c /deploy/crashreporter/docker-compose.yml crashreporter;
