name: Publish Backend Docker Image

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/docker.yml'
      - 'src/**'
      - '!src/BUTR.CrashReportViewer/Client/**'
      - 'build/**'
  workflow_dispatch:

jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./src
        file: ./src/BUTR.CrashReportViewer/Server/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: docker.pkg.github.com/BUTR/BUTR.CrashReportViewer/crashreportviewer:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
