# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - BUTRCrashReportViewer

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/docker.yml'
      - 'src/**'
      - '!src/BUTR.CrashReportViewer/Client/**'
      - 'build/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: 'backend-docker'
          allowed-conclusions: success
    
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BUTRCrashReportViewer'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_387ec3bb61a24c6696f242e52da67a97 }}
          images: 'ghcr.io/butr/crashreportviewer:latest'
